# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-ast
    -   id: check-toml
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    # -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
    -   id: python-no-log-warn
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0  # or master if you're bold
    hooks:
    -   id: interrogate
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
# -   repo: https://github.com/psf/black
#     rev: 23.1.0
#     hooks:
#     -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 0b037c2
#     hooks:
#     -   id: mypy
# -   repo: https://github.com/PyCQA/isort
#     rev: 5.12.0
#     hooks:
#     -   id: isort
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.19
    hooks:
    -   id: pymarkdown
-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: check-poetry
